### ISSUE TITLE
DIT gives different results than DIF

### ISSUE THREAD

**Issue by maximevince** [stg/SYLT-FFT#3]
When using the default "DIT" (division in time), which is supposedly the faster way to calculate an FFT,
I get results that are strongly different than with the "DIF" (division in frequency).
Furthermore "DIF" output seems to match 'R' and python's FFT output closely, while "DIT" does not for a 512 sample real input dataset (Fs=200Hz). (There are additional frequency components present in the DIT) 

Dataset:
http://pastebin.com/hvqq57pR

Results:
DIF (seems correct):
http://pastebin.com/scqedLmh

DIT (seems erronoes):
http://pastebin.com/phDxJYCA

Also, on my Cortex-M0, DIF is ~ 5% faster, instead of being slower as suggested by the comments.

Is there more rounding happening when using DIT, or some other optimization that might introduce these artefacts? Or am I completely missing something here, which is also quite likely :)

**Comment by stg** [comment]
Mathematically there is no difference in performance between DIF and DIT - the number of calculations are identical. However in a complex environment involving target register limitations, compiler decisions and the target instruction set it may very well turn out that one is faster than the other. The default is set up to be the faster version for my use case (Cortex M4).

Without studying the results in detail it seems the difference between the data sets is in the range of a few integers only and I would assume this is due to rounding. FFT is calculated in a repetitive process and any rounding error from the previous stage will pass on to the next stage where it may futher grow or shrink depending on rounding errors at this stage. A 256 point FFT has 8 stages and may therefore yield errors of up to +/- 8 but can be slightly limited by enabling rounding in the configuration.

All fixed-point implementations of DSP algorithms has issues with rounding resulting in this sort of noise, but it is most often mitigated by using large signals such that the noise level becomes insignificant in relation to the signal level.

The numbers you are getting are very small, hence these rounding errors end up being significant in relation to the actual data. An error of just one for a result of 20 is 5%. Anwother wording is to say your signal to noise ratio is very high.

SYLT-FFT works with 32 bit integers. The input for the FFT should utilize as much as possible of this number space to yield the highest possible signal to noise ratio. Your dataset appears to contain a signal with a peak amplitude of a few hundred while 32-bit handles tens of billions. By simple shifting or multiplying your input signal by a suitable factor will give you much better results. Noise will still be there and with the same numerical strength, but in relation to the signal it will be reduced from near one percent down to one millionth of a percent which is more than adequate for most uses.

SYLT-FFT was written to provide high performance, not high accuracy at the lowest bit levels - however this is a problem you would see with any fixed-point implementation if fed with signals that are too weak.

I hope this answers your question, if it does please close the issue - if not ask further :)

**Comment by maximevince** [comment]
Hi @stg 
thanks again for the detailed answers you are providing.
You are absolutely right about the SNR of the input signals.
Explanation is clear; I'll try your suggestions!
